# Generated by Django 6.0.3 on 2026-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutestore', '0008_remove_order_created_at_order_address_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
